### ISSUE TITLE
LongPoll requests fail when made from a different origin

### ISSUE THREAD

**Issue by jerel** [jerel/phoenix_js#1]
@chrismccord if you get time could you take a look through /server on the [bugfix/cors](/jerel/phoenix_js/tree/bugfix/cors) branch to make sure I'm not missing something. I've tried various configs and the score is still CORS: 1, Jerel: 0

**Comment by willrax** [comment]
After playing around with this tonight, it looks like Phoenix isn't returning the headers required for a cross site request. It should respond with the `Access-Control-Allow-Origin` ones in there.

**Comment by willrax** [comment]
It looks like it does this for a preflight 'OPTIONS' check but not for a `GET`.

https://github.com/phoenixframework/phoenix/blob/b1004d4e6eed566a638a2a926d17cacc3d852fe1/lib/phoenix/transports/long_poll.ex#L85

**Comment by chrismccord** [comment]
@jerel do you have the host listed in the `check_origin` options on the phoenix side?

**Comment by willrax** [comment]
I've managed to get this working by adding this to the long poll transport:

`|> put_resp_header("access-control-allow-origin", "*")`

```
  def call(conn, {endpoint, handler, transport}) do
    {_, opts} = handler.__transport__(transport)

    conn
    |> fetch_query_params
    |> Plug.Conn.fetch_query_params
    |> Transport.transport_log(opts[:transport_log])
    |> Transport.force_ssl(handler, endpoint, opts)
    |> Transport.check_origin(handler, endpoint, opts, &status_json(&1, %{}))
    |> put_resp_header("access-control-allow-origin", "*")
    |> dispatch(endpoint, handler, transport, opts)
  end
```

**Comment by jerel** [comment]
@chrismccord I currently have it set to `false` in the dev config: https://github.com/jerel/phoenix_js/blob/master/server/config/dev.exs#L14 In my debugging the other day setting the host or `check_origin` didn't seem to have an effect

**Comment by willrax** [comment]
@chrismccord the check_origin just seems to allow the connection to go through if the requesting host is in the list. I can't see a point where it sets the correct headers that the browser needs.

**Comment by jerel** [comment]
@willrax thanks, your patch does fix my cross origin test locally. Theoretically it's safe to `access-control-allow-origin` on all requests (at least to the longpoll endpoint) https://annevankesteren.nl/2012/12/cors-101

**Comment by willrax** [comment]
Yeah, I think if you're using the check_origin method it should be fine as well because you are still doing some sort of access restriction.

**Comment by jerel** [comment]
@willrax thanks for working on the fix for this!
