### ISSUE TITLE
missing :adapter  configuration in config :server !!

### ISSUE THREAD

**Issue by ramstein74** [jerel/phoenix_js#4]
I tried npm install --save-dev phoenix_js 
but phoenix is complaining about it
Says "missing :adapter  configuration missing. What should i do next ?

![image](https://cloud.githubusercontent.com/assets/1210858/12194872/25fc816a-b5eb-11e5-8f1c-5060a9a30745.png)

**Comment by jerel** [comment]
Check your Phoenix config file. That error message comes from elixir and must have just showed up at the same time by coincidence. Maybe you restarted your server after you installed this package?

**Comment by ramstein74** [comment]
i solved it going to your package inside phoenix_js/server/lib/server/repo.ex
and adding the following  to repo.ex

  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "my_app_dev",
  pool_size: 10
end

Now it works....

**Comment by jerel** [comment]
That server directory is only meant to be used by us as we develop the package, not by applications that consume the package. You should be able to do `npm install --save-dev phoenix_js` in an existing phoenix project and have it place the javascript in `node_modules`. The files in `lib` are what brunch, webpack, or etc will pull in to compile.

**Comment by ramstein74** [comment]
If i remove the code i showed you to your repo.ex the phoenix console gives
me the same error..
I´m using browserify to build a single app.js file.
then i place that file in the priv/static/js/ folder

Thank you

2016-01-08 13:56 GMT+00:00 Jerel Unruh notifications@github.com:
